import {Configuration, UsersApi} from '../generated/jericho';
import config from '../config';

export const apiConfig = new Configuration({
  basePath: config.jerichoApiHost,
  accessToken:
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJNbnpCVGNXQ205SjAtZkR5WG1JNSJ9.eyJpc3MiOiJodHRwczovL2Rldi14bHJhaGMycXkxd3FkZGY4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExMTc3NjY4NjEwNjgwODcxNDcyOSIsImF1ZCI6WyJodHRwczovL2plcmljaG8uZGV2LmNvbSIsImh0dHBzOi8vZGV2LXhscmFoYzJxeTF3cWRkZjgudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY5NzQxMjk0NCwiZXhwIjoxNjk3NDk5MzQ0LCJhenAiOiJiTTNXclZJcVhKbXJCa0V0eTBvZlM4UnlCdnJNMTRQbCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.BlehsynoolLZL5piat-VIOZfPQvuWn-snGoU05sDZoqfwgsthHih7DERSvoaDf24VhDgY7fHr8aCKpIE_b3IpPpYOuOZCtVF6JGZ-ADWKNrM8Mqsu0J50RB5GhxUbaCNbdMkToZ_GROOk2GzebS7piJt7DVmVQTMNXxktJPWuANFzeXn7tn4fHj9H1bVqWY8ZNpJt5N4WuaBg247UdzO67xFIg5WxKhLxkMelP79l3hUbukygM53WfNK3ZwefagWmL59ucPUCwEXLsS-eJ7-i4OK4hOm_qI9QQcjoXEuXJT2AOqcyXKY-aXoTfy84AGgbodyywk5K_e8S71t5VeLBQ',
});

export const usersApi = new UsersApi(apiConfig);
