pg_host: str = "localhost"
pg_user: str = "postgres"
pg_password: str = "admin"
auth0_domain: str = "https://dev-xlrahc2qy1wqddf8.us.auth0.com/"
auth0_audience: str = "https://jericho.dev.com"
alembic_dir: str = "/Users/achew/bibli/jericho/app/src/db/alembic"
